#Despliegue de agente y broker
services:
  agente:
    container_name: agente_W_RS
    build: ./agente_W_RS
    ports:
      - "4451:4451"
    volumes:
      - /data:/data

  broker:
    container_name: broker_D_W_RS
    build: ./broker_D_W_RS
    ports:
      - "4450:4450"
    volumes:
      - /data:/data
