# Etapa 1: build con Node
FROM node:18-alpine AS builder

WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias necesarias
RUN npm install
#RUN npm install -D tailwindcss postcss autoprefixer @tailwindcss/vite
#RUN npm install chart.js react-chartjs-2
#RUN npm install axios

# Copiar el resto del proyecto
COPY . .

# Build de producción
RUN npm run build

# Etapa 2: producción usando NGINX
FROM nginx:alpine

# Copia el build de React a la ruta pública de nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Opcional: reemplazar configuración por defecto de nginx si tienes una personalizada
# COPY nginx.conf /etc/nginx/nginx.conf

# Expone el puerto 80
EXPOSE 80

# Comando por defecto para nginx
CMD ["nginx", "-g", "daemon off;"]
